### ISSUE TITLE
yeah you rule!

### ISSUE THREAD

**Issue by Outfit8TSB** [YvanMazy/TransferProxy#4]
however 1 thing, does it exit server in java client or just cause portal event like bungeecord?

**Comment by YvanMazy** [comment]
Thank you for your attention to this project.

To answer your question: TransferProxy works in a similar way to BungeeCord, in that the player is not disconnected when changing servers. However, unlike BungeeCord, it doesn't constantly host the connection. Typically, it acts as an intermediary between servers, like a bridge.

I'm not sure I understood your initial question, so if you're missing any information I recommend you consult the wiki. Otherwise you can answer me in this issue.

**Comment by Outfit8TSB** [comment]
why did i named the issue it like this because this api literally can used to transfer ViaProxy Public Wildcard Address(address_port_version.viaproxy.hostname)

imagine using this to remake a viaproxy command that used to worked on RK_01's ViaProxyConnect Server.
isn't it cool?

**Comment by YvanMazy** [comment]
Yes, it's really cool! It's an interesting way of using it, don't forget that to connect to a TransferProxy you must have a client version greater than or equal to 1.20.5.

**Comment by Outfit8TSB** [comment]
i am making this program into a spigot bootstrap like Geyser Did.

**Comment by YvanMazy** [comment]
Hello! Do you have any other questions? The issue can be closed, right?

**Comment by Outfit8TSB** [comment]
yes it can be closed.
